### ISSUE TITLE
Babashka test/*report-counters* is a ref instead of an atom for bb >= 1.1.171

### ISSUE THREAD

**Issue by borkdude** [matthewdowney/rich-comment-tests#18]
The tests are failing with bb >= 1.1.171 due to binding `test/*report-counters*` to an atom instead of a ref. bb 1.1.171 fixes this incompatibility with Clojure. I think a lot of `.cljc` files could become `.clj` files due to this change.

**Comment by matthewdowney** [comment]
Ah just saw this also, got it! 

Perhaps the way to go is a macro which checks the Babashka version (if on bb) and emits atom / ref accordingly, to maintain backwards compatibility for anyone running older Babashka versions. 

I'll give this a shot later today.

**Comment by borkdude** [comment]
I'd say just drop support for the older babashka versions to keep it simple, this will also encourage people to upgrade. There's usually not a reason not to upgrade.
