### ISSUE TITLE
Update clojars version please

### ISSUE THREAD

**Issue by licht1stein** [matthewdowney/rich-comment-tests#21]
I'm getting this error when using the git version, I can prepare a PR with ci automatically pushing to Clojars, all you'll need to do is add secrets to the repo.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/35418634/235293634-27fb7264-0cac-4914-b90e-b62b003f8653.png">

**Comment by matthewdowney** [comment]
Hi @licht1stein , sorry this is happening, great idea to push to Clojars as well.

Any idea what exactly is going on with the github dependency, so I can try to fix it for anyone who isn't going to use the Clojars coordinates / avoid messing it up in the future?

**Comment by licht1stein** [comment]
Thanks for merging the PR. I have no idea why ions is not seeing this, to me it looks like a bug in ions, but it's way above my level of understanding :)

**Comment by licht1stein** [comment]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/35418634/235304596-04bc232e-af3d-4ed4-93cf-bb9a1d45ec4c.png">

Everything works now :)

**Comment by matthewdowney** [comment]
I do remember hitting some issues with the git coords due to https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/, but I think this would have showed up sooner / presented a different error message if it were the cause for you as well.

**Comment by licht1stein** [comment]
I just started using your lib yesterday for the first time, I think it's an amazing improvement in usability over hyperfiddle :)
