### ISSUE TITLE
Tries to test comments not marked with the meta tag

### ISSUE THREAD

**Issue by licht1stein** [matthewdowney/rich-comment-tests#23]
I've got this in my source file:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/35418634/235309218-e7e1c3f4-24dc-4c61-af41-1957cfb6a653.png">

If I understand correctly, only the second form should be tested, but I got a failed test from the first comment. Is this the intended behavior?

**Comment by licht1stein** [comment]
Sorry, I had a rogue update in code that broke the second macro

**Comment by matthewdowney** [comment]
No worries, glad this turned out not to be a bug!
