### ISSUE TITLE
Allow whitespace between semicolon and arrow (;; =>)

### ISSUE THREAD

**Issue by lilactown** [matthewdowney/rich-comment-tests#3]
Using Emacs + CIDER, I often use `cider-pprint-eval-last-sexp-to-comment` to print the result to a comment. It outputs it like so

```clojure
(+ 1 1)
;; => 2
```

The only difference between that and what RCT expects is there's a space between the leading `;;` and the arrow `=>`.

I think it'd be great to support this syntax out of the box, to allow easy usage with CIDER.

**Comment by matthewdowney** [comment]
Agreed, thank you!
