### ISSUE TITLE
Automatically quote result when used with =>

### ISSUE THREAD

**Issue by lilactown** [matthewdowney/rich-comment-tests#5]
This might be controversial, but I thought I'd throw it out there: I think that when reading the expected result, the form should be automatically quoted. E.g.

```clojure
^:rct/test
(comment
  (map inc [1 2 3])
  ;;=> (1 2 3)
  )
```

Today, this would throw with the error
```
Uncaught exception, not in assertion.
expected: nil
  actual: java.lang.ClassCastException: class java.lang.Long cannot be cast to class clojure.lang.IFn (java.lang.Long is in module java.base of loader 'bootstrap'; clojure.lang.IFn is in unnamed module of loader 'app')
```

Because when we emit the test code, it evaluates the result form as an expression.

My suggested change is to treat the result form as data, so that the above test would pass.

**Comment by matthewdowney** [comment]
Hmm yes this makes sense to me, and I like your solution. 

Initially I was thinking it might be an issue for matcho patterns, for example here I'd want it to use `int?` rather than `'int?` as the pattern:

```clojure
^:rct/test
(comment
  (+ 5 5) ;=>> int?
)
```

but this still works in your implementation, so no downsides that I can see. 

The only thing I can think of that worked before but will not work now is something like

```clojure
:rct/test
(comment 
  (def expected 10)
  (+ 5 5) ;=> expected
)
```

But I don't that that is a particularly natural use of a comment anyway, and if anyone wants to do it they can just `(+ 5 5) ;=>> expected`, making more explicit that it's not an assertion of literal equality.

So, fantastic addition, thank you!

**Comment by lilactown** [comment]
Great! Thanks for taking a look at both my PRs 💙

**Comment by sogaiu** [comment]
I guess it's too late by now, but this feature seems to work against being able to express the expected result via a computation / evaluation.

As an example, given:

```clojure
(defn double                                                                         
  [n]                                                                                
  (* 2 n))                                                                           
```

I was hoping to be able to do this:

```clojure
^:rct/test                                                                           
(comment                                                                             
                                                                                      
  (double 4.2)
  ;=>
  (* 2 4.2)

  )
```

ATM, executing the test here results in something like:

```
expected: (= (double 4.2) (* 2 4.2))
  actual: (not (= 8.4 (* 2 4.2)))
```

Is there any way one might avoid having to do the following?

```clojure
^:rct/test                                                                           
(comment                                                                             
                                                                                      
  (double 4.2)
  ;=>
  8.4

  )
```

May be I missed some option -- sorry if I did 😅 

---

P.S. Thanks for `rich-comment-tests` BTW.  I really appreciate the minimality this provides.  I find that this type of system helps one to hold on to exploratory expressions not only for testing but as illustrative examples for future readers.

**Comment by matthewdowney** [comment]
hey there @sogaiu - `;=>>` should work for this. let me know if the below works for you as expected:

```clojure
^:rct/test
(comment
  (defn double' [n] (* 2 n))
  (double' 4.2) ;=>> (* 2 4.2)
  )
```

**Comment by sogaiu** [comment]
@matthewdowney Works great!

TYVM!
