### ISSUE TITLE
`run-ns-tests!` can't find the source file for a namespace if the namespace doesn't have public vars

### ISSUE THREAD

**Issue by matthewdowney** [matthewdowney/rich-comment-tests#9]
### Problem

The following produces an error:

```clojure
(ns foo)

^:rct/test
(comment
  (+ 1 1) ;=> 2
)

(require '[com.mjdowney.rich-comment-tests :as rct])
(rct/run-ns-tests! *ns*)
```

### Mechanism 

When `run-ns-tests!` takes a namespace, it attempts to find the path to the corresponding source file by looking at the `:file` metadata attribute for each public var in the namespace. 
 
https://github.com/matthewdowney/rich-comment-tests/blob/d351ad9bd8cb167d533f42ffe83e748c311c1fee/src/com/mjdowney/rich_comment_tests.clj#L245-L261

### One solution
The code in the `test-runner` namespace builds an index of `namespace -> [source-file-path]` that it uses to run tests for all the namespaces in a file tree. There should be a delay somewhere with the same information that `run-ns-tests!` can use as a fallback.

**Comment by matthewdowney** [comment]
If the two use cases for RCT are:

1. Quickly run tests in the current namespace at the REPL
2. Run all rich comment tests across the codebase

and this issue primarily affects (1), then another solution is just to check if the ns to test is `*ns*`, and if so, use `*file*`. 

This doesn't support the case where one wants to explicitly test a different namespace which doesn't have any public vars, but in that case somebody could use `run-file-tests!` and supply the source file explicitly.

In such a case, users would have the options of using the tools in the `test-runner` ns to read through all the files on the classpath and build their own map of ns -> source file, if they so choose. 

E.g.
```clojure
; Get normal directories (i.e. not dependency JARS) from the classpath
(let [cp-sep (System/getProperty "path.separator")
      cp-dirs (into #{}
                (comp
                  (map clojure.java.io/file)
                  (filter #(.isDirectory %))
                  (map str))
                (.split (System/getProperty "java.class.path") cp-sep))]
  ; Read their contents and build a map from namespace -> [source-file]
  (com.mjdowney.rich-comment-tests.test-runner/ns->files cp-dirs #(.isFile %)))
```

**Comment by matthewdowney** [comment]
Actually, the solution here is probably just to send 

```clojure
(com.mjdowney.rich-comment-tests/run-file-tests! *file* *ns*)
```

to the REPL instead.

**Comment by sogaiu** [comment]
I tried the suggested:

```clojure
(com.mjdowney.rich-comment-tests/run-file-tests! *file* *ns*)
```

in a setup with babashka + nrepl + cider and didn't manage to get it to work...presumably because `*file*` yields values that look like:

```
"*cider-repl <path>:localhost:1667(clj)*"
```

(where &lt;path&gt; was the project root directory path relative to `HOME`).

A slight modification seems to be working here, which is to use the following emacs function to send a similar form using a constructed full path in place of `*file*`:

```emacs-lisp
(defun rct-run-file-tests ()
  (interactive)
  (cider-interactive-eval
   (concat "("
           "(requiring-resolve 'com.mjdowney.rich-comment-tests/run-file-tests!)"
           ;; XXX: some paths might not work due to missing escaping
           " \"" (buffer-file-name) "\" "
           "*ns*"
           ")")))
```

Not as nice perhaps, but at least works for cider / emacs users?

May be there is some simpler solution though...
